enableGlobalCache: true

# Der nodeLinker entscheidet, wie Yarn Packages installiert
# pnp - Plug'n'Play Modus (empfohlen für neue Projekte)
# node-modules - Klassischer node_modules Modus
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs
