// Application Interfaces for Heat Pump Manufacturing Company
// Integration interfaces supporting IoT platform and enterprise applications

import { Session } from 'neo4j-driver'

export async function createHeatPumpApplicationInterfaces(session: Session): Promise<void> {
  console.log('Creating Application Interfaces for Heat Pump Manufacturing...')

  const query = `
    CREATE 
    // IoT Platform Interfaces
    (iotDeviceApi:ApplicationInterface {
      id: "hp-interface-iot-device-api",
      name: "IoT Device Management API",
      description: "RESTful API for managing heat pump IoT devices, configuration, and remote control",
      interfaceType: "API",
      protocol: "REST",
      version: "v2.1",
      status: "ACTIVE",
      introductionDate: date("2024-01-15"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (iotTelemetryApi:ApplicationInterface {
      id: "hp-interface-iot-telemetry-api",
      name: "IoT Telemetry Ingestion API",
      description: "High-throughput streaming API for real-time heat pump sensor data ingestion",
      interfaceType: "API",
      protocol: "TCP",
      version: "v1.5",
      status: "ACTIVE",
      introductionDate: date("2024-01-15"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (energyAnalyticsApi:ApplicationInterface {
      id: "hp-interface-energy-analytics-api",
      name: "Energy Analytics API",
      description: "API for retrieving energy consumption data, efficiency metrics, and optimization recommendations",
      interfaceType: "API",
      protocol: "REST",
      version: "v1.3",
      status: "ACTIVE",
      introductionDate: date("2024-02-01"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // ERP System Interfaces
    (erpCustomerApi:ApplicationInterface {
      id: "hp-interface-erp-customer-api",
      name: "ERP Customer Data API",
      description: "SOAP interface for customer master data synchronization with CRM and service systems",
      interfaceType: "API",
      protocol: "SOAP",
      version: "v3.0",
      status: "ACTIVE",
      introductionDate: date("2024-01-01"),
      throughput: "1,000 requests/minute",
      latency: "< 1000ms",
      securityLevel: "HIGH",
      rateLimiting: "200 calls/hour per system",
      documentation: "https://erp.thermo-dynamics.com/api/customer/wsdl",
      endpoint: "https://erp.thermo-dynamics.com/api/customer/v3",
      lastUpdated: date("2024-05-10"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (erpProductApi:ApplicationInterface {
      id: "hp-interface-erp-product-api",
      name: "ERP Product Information API",
      interfaceType: "API",
      description: "Product catalog, specifications, and bill of materials API for manufacturing and sales systems",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v2.5",
      status: "ACTIVE",
      availability: "99.7%",
      throughput: "2,000 requests/minute",
      latency: "< 300ms",
      securityLevel: "MEDIUM",
      rateLimiting: "1000 calls/hour per application",
      documentation: "https://api.thermo-dynamics.com/product/v2/docs",
      endpoint: "https://api.thermo-dynamics.com/product/v2",
      lastUpdated: date("2024-07-30"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (erpOrderApi:ApplicationInterface {
      id: "hp-interface-erp-order-api",
      name: "ERP Order Management API",
      interfaceType: "API",
      description: "Order processing, status tracking, and fulfillment API for sales and manufacturing integration",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v2.2",
      status: "ACTIVE",
      availability: "99.9%",
      throughput: "3,000 requests/minute",
      latency: "< 250ms",
      securityLevel: "HIGH",
      rateLimiting: "500 calls/hour per user",
      documentation: "https://api.thermo-dynamics.com/orders/v2/docs",
      endpoint: "https://api.thermo-dynamics.com/orders/v2",
      lastUpdated: date("2024-08-05"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // CRM System Interfaces
    (crmServiceApi:ApplicationInterface {
      id: "hp-interface-crm-service-api",
      name: "CRM Service Management API",
      interfaceType: "API",
      description: "Customer service case management, ticket routing, and resolution tracking API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.8",
      status: "ACTIVE",
      availability: "99.6%",
      throughput: "1,500 requests/minute",
      latency: "< 400ms",
      securityLevel: "HIGH",
      rateLimiting: "300 calls/hour per agent",
      documentation: "https://api.thermo-dynamics.com/service/v1/docs",
      endpoint: "https://api.thermo-dynamics.com/service/v1",
      lastUpdated: date("2024-07-10"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (crmInstallerApi:ApplicationInterface {
      id: "hp-interface-crm-installer-api",
      name: "CRM Installer Portal API",
      interfaceType: "API",
      description: "API for certified installer access to product information, training materials, and support tools",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + Certificate",
      version: "v1.4",
      status: "ACTIVE",
      availability: "99.4%",
      throughput: "800 requests/minute",
      latency: "< 600ms",
      securityLevel: "HIGH",
      rateLimiting: "200 calls/hour per installer",
      documentation: "https://installer.thermo-dynamics.com/api/docs",
      endpoint: "https://installer.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-06-15"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // Manufacturing Interfaces
    (mesProductionApi:ApplicationInterface {
      id: "hp-interface-mes-production-api",
      name: "MES Production Control API",
      interfaceType: "API",
      description: "OPC UA interface for real-time production data exchange and manufacturing execution control",
      protocol: "TCP",
      dataFormat: "OPC UA",
      authenticationMethod: "X.509 Certificates",
      version: "v1.04",
      status: "ACTIVE",
      availability: "99.95%",
      throughput: "1,000 operations/second",
      latency: "< 100ms",
      securityLevel: "CRITICAL",
      rateLimiting: "No limit",
      documentation: "Internal MES documentation",
      endpoint: "opc.tcp://mes.thermo-dynamics.local:4840",
      lastUpdated: date("2024-07-20"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (qualityTestApi:ApplicationInterface {
      id: "hp-interface-quality-test-api",
      name: "Quality Testing Interface",
      interfaceType: "API",
      description: "API for automated quality testing equipment integration and test result management",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key",
      version: "v2.0",
      status: "ACTIVE",
      availability: "99.8%",
      throughput: "500 requests/minute",
      latency: "< 200ms",
      securityLevel: "HIGH",
      rateLimiting: "Unlimited for testing equipment",
      documentation: "https://quality.thermo-dynamics.com/api/docs",
      endpoint: "https://quality.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-10"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // External Partner Interfaces
    (supplierPortalApi:ApplicationInterface {
      id: "hp-interface-supplier-portal-api",
      name: "Supplier Portal API",
      interfaceType: "API",
      description: "B2B API for supplier integration, purchase orders, delivery schedules, and invoice processing",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + API Key",
      version: "v1.6",
      status: "ACTIVE",
      availability: "99.5%",
      throughput: "1,200 requests/minute",
      latency: "< 800ms",
      securityLevel: "HIGH",
      rateLimiting: "100 calls/hour per supplier",
      documentation: "https://supplier.thermo-dynamics.com/api/docs",
      endpoint: "https://supplier.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-06-30"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (smartGridApi:ApplicationInterface {
      id: "hp-interface-smart-grid-api",
      name: "Smart Grid Integration API",
      interfaceType: "API",
      description: "API for smart grid communication, demand response, and energy market participation",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + Digital Certificates",
      version: "v1.2",
      status: "IN_DEVELOPMENT",
      availability: "99.0%",
      throughput: "2,000 requests/minute",
      latency: "< 300ms",
      securityLevel: "CRITICAL",
      rateLimiting: "500 calls/hour per grid operator",
      documentation: "https://api.thermo-dynamics.com/grid/docs",
      endpoint: "https://api.thermo-dynamics.com/grid/v1",
      lastUpdated: date("2024-08-15"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // Strategic Management Interfaces
    (strategyApi:ApplicationInterface {
      id: "hp-interface-strategy-api",
      name: "Strategic Portfolio Management API",
      interfaceType: "API",
      description: "API for strategic planning, portfolio management, and business intelligence integration",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.0",
      status: "ACTIVE",
      availability: "99.5%",
      throughput: "200 requests/minute",
      latency: "< 500ms",
      securityLevel: "HIGH",
      rateLimiting: "50 calls/hour per user",
      documentation: "https://strategy.thermo-dynamics.com/api/docs",
      endpoint: "https://strategy.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-08-01"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (riskMgmtApi:ApplicationInterface {
      id: "hp-interface-risk-mgmt-api",
      name: "Risk Management API",
      interfaceType: "API",
      description: "Enterprise risk assessment, compliance tracking, and governance reporting API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + MFA",
      version: "v2.1",
      status: "ACTIVE",
      availability: "99.8%",
      throughput: "300 requests/minute",
      latency: "< 400ms",
      securityLevel: "CRITICAL",
      rateLimiting: "100 calls/hour per user",
      documentation: "https://risk.thermo-dynamics.com/api/docs",
      endpoint: "https://risk.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-07-25"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (sustainabilityApi:ApplicationInterface {
      id: "hp-interface-sustainability-api",
      name: "Sustainability Tracking API",
      interfaceType: "API",
      description: "Carbon footprint tracking, ESG reporting, and environmental compliance API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key",
      version: "v1.3",
      status: "ACTIVE",
      availability: "99.2%",
      throughput: "400 requests/minute",
      latency: "< 600ms",
      securityLevel: "MEDIUM",
      rateLimiting: "200 calls/hour per department",
      documentation: "https://sustainability.thermo-dynamics.com/api/docs",
      endpoint: "https://sustainability.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-08-20"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (marketIntelApi:ApplicationInterface {
      id: "hp-interface-market-intel-api",
      name: "Market Intelligence API",
      interfaceType: "API",
      description: "Competitive analysis, market trends, and business intelligence data API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.1",
      status: "ACTIVE",
      availability: "99.3%",
      throughput: "150 requests/minute",
      latency: "< 800ms",
      securityLevel: "HIGH",
      rateLimiting: "75 calls/hour per analyst",
      documentation: "https://intelligence.thermo-dynamics.com/api/docs",
      endpoint: "https://intelligence.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-07-15"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // R&D and Engineering Interfaces
    (plmApi:ApplicationInterface {
      id: "hp-interface-plm-api",
      name: "Modern PLM API",
      interfaceType: "API",
      description: "Product lifecycle management, engineering change management, and CAD integration API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v3.0",
      status: "ACTIVE",
      availability: "99.7%",
      throughput: "800 requests/minute",
      latency: "< 350ms",
      securityLevel: "HIGH",
      rateLimiting: "500 calls/hour per engineer",
      documentation: "https://plm.thermo-dynamics.com/api/docs",
      endpoint: "https://plm.thermo-dynamics.com/api/v3",
      lastUpdated: date("2024-08-10"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (cfdApi:ApplicationInterface {
      id: "hp-interface-cfd-api",
      name: "CFD Simulation API",
      interfaceType: "API",
      description: "Computational fluid dynamics simulation job management and result retrieval API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key + LDAP",
      version: "v2.0",
      status: "ACTIVE",
      availability: "99.1%",
      throughput: "50 requests/minute",
      latency: "< 2000ms",
      securityLevel: "MEDIUM",
      rateLimiting: "20 simulations/day per user",
      documentation: "https://cfd.thermo-dynamics.com/api/docs",
      endpoint: "https://cfd.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-07-30"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (testDataApi:ApplicationInterface {
      id: "hp-interface-test-data-api",
      name: "Test Data Management API",
      interfaceType: "API",
      description: "Laboratory test data collection, analysis, and reporting API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.5",
      status: "ACTIVE",
      availability: "99.6%",
      throughput: "600 requests/minute",
      latency: "< 300ms",
      securityLevel: "MEDIUM",
      rateLimiting: "1000 calls/hour per lab",
      documentation: "https://testdata.thermo-dynamics.com/api/docs",
      endpoint: "https://testdata.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-08-05"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (innovationApi:ApplicationInterface {
      id: "hp-interface-innovation-api",
      name: "Innovation Management API",
      interfaceType: "API",
      description: "Idea submission, evaluation, and innovation project tracking API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.2",
      status: "ACTIVE",
      availability: "99.0%",
      throughput: "100 requests/minute",
      latency: "< 700ms",
      securityLevel: "MEDIUM",
      rateLimiting: "50 calls/hour per user",
      documentation: "https://innovation.thermo-dynamics.com/api/docs",
      endpoint: "https://innovation.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-06-20"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (ipMgmtApi:ApplicationInterface {
      id: "hp-interface-ip-mgmt-api",
      name: "IP Management API",
      interfaceType: "API",
      description: "Intellectual property portfolio management and patent tracking API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + MFA",
      version: "v1.4",
      status: "ACTIVE",
      availability: "99.5%",
      throughput: "80 requests/minute",
      latency: "< 500ms",
      securityLevel: "HIGH",
      rateLimiting: "40 calls/hour per legal user",
      documentation: "https://ip.thermo-dynamics.com/api/docs",
      endpoint: "https://ip.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-07-10"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // Advanced Manufacturing Interfaces
    (mrpApi:ApplicationInterface {
      id: "hp-interface-mrp-api",
      name: "Advanced MRP API",
      interfaceType: "API",
      description: "Material requirements planning with AI forecasting and supply chain optimization",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v2.2",
      status: "ACTIVE",
      availability: "99.9%",
      throughput: "1500 requests/minute",
      latency: "< 200ms",
      securityLevel: "HIGH",
      rateLimiting: "2000 calls/hour per system",
      documentation: "https://mrp.thermo-dynamics.com/api/docs",
      endpoint: "https://mrp.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-15"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (warehouseApi:ApplicationInterface {
      id: "hp-interface-warehouse-api",
      name: "Warehouse Management API",
      interfaceType: "API",
      description: "Automated warehouse operations, inventory tracking, and robotics integration API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key",
      version: "v3.1",
      status: "ACTIVE",
      availability: "99.8%",
      throughput: "2000 requests/minute",
      latency: "< 150ms",
      securityLevel: "MEDIUM",
      rateLimiting: "5000 calls/hour per warehouse",
      documentation: "https://warehouse.thermo-dynamics.com/api/docs",
      endpoint: "https://warehouse.thermo-dynamics.com/api/v3",
      lastUpdated: date("2024-08-12"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (predictiveMaintenanceApi:ApplicationInterface {
      id: "hp-interface-predictive-maintenance-api",
      name: "Predictive Maintenance API",
      interfaceType: "API",
      description: "AI-powered predictive maintenance analytics and equipment health monitoring API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.8",
      status: "ACTIVE",
      availability: "99.4%",
      throughput: "800 requests/minute",
      latency: "< 400ms",
      securityLevel: "MEDIUM",
      rateLimiting: "1000 calls/hour per facility",
      documentation: "https://maintenance.thermo-dynamics.com/api/docs",
      endpoint: "https://maintenance.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-08-18"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (energyMgmtApi:ApplicationInterface {
      id: "hp-interface-energy-mgmt-api",
      name: "Energy Management API",
      interfaceType: "API",
      description: "Factory energy monitoring, optimization, and sustainability reporting API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key",
      version: "v2.0",
      status: "ACTIVE",
      availability: "99.6%",
      throughput: "1000 requests/minute",
      latency: "< 250ms",
      securityLevel: "MEDIUM",
      rateLimiting: "2000 calls/hour per facility",
      documentation: "https://energy.thermo-dynamics.com/api/docs",
      endpoint: "https://energy.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-08"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // Sales & Marketing Interfaces
    (ecommerceApi:ApplicationInterface {
      id: "hp-interface-ecommerce-api",
      name: "B2B E-Commerce API",
      interfaceType: "API",
      description: "Online ordering, product catalog, and customer portal API for distributors",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v2.4",
      status: "ACTIVE",
      availability: "99.7%",
      throughput: "1200 requests/minute",
      latency: "< 300ms",
      securityLevel: "HIGH",
      rateLimiting: "500 calls/hour per customer",
      documentation: "https://shop.thermo-dynamics.com/api/docs",
      endpoint: "https://shop.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-20"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (digitalMarketingApi:ApplicationInterface {
      id: "hp-interface-digital-marketing-api",
      name: "Digital Marketing API",
      interfaceType: "API",
      description: "Marketing automation, lead tracking, and campaign management API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key",
      version: "v1.6",
      status: "ACTIVE",
      availability: "99.3%",
      throughput: "600 requests/minute",
      latency: "< 400ms",
      securityLevel: "MEDIUM",
      rateLimiting: "300 calls/hour per campaign",
      documentation: "https://marketing.thermo-dynamics.com/api/docs",
      endpoint: "https://marketing.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-07-28"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (configuratorApi:ApplicationInterface {
      id: "hp-interface-configurator-api",
      name: "Product Configurator API",
      interfaceType: "API",
      description: "Heat pump system configuration, pricing, and 3D visualization API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v2.1",
      status: "ACTIVE",
      availability: "99.5%",
      throughput: "400 requests/minute",
      latency: "< 600ms",
      securityLevel: "MEDIUM",
      rateLimiting: "200 calls/hour per session",
      documentation: "https://configure.thermo-dynamics.com/api/docs",
      endpoint: "https://configure.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-14"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (partnerMobileApi:ApplicationInterface {
      id: "hp-interface-partner-mobile-api",
      name: "Partner Mobile API",
      interfaceType: "API",
      description: "Mobile app backend for installer tools, product info, and support features",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + Device ID",
      version: "v1.7",
      status: "ACTIVE",
      availability: "99.2%",
      throughput: "800 requests/minute",
      latency: "< 350ms",
      securityLevel: "HIGH",
      rateLimiting: "500 calls/hour per installer",
      documentation: "https://mobile.thermo-dynamics.com/api/docs",
      endpoint: "https://mobile.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-08-16"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (socialListeningApi:ApplicationInterface {
      id: "hp-interface-social-listening-api",
      name: "Social Media Listening API",
      interfaceType: "API",
      description: "Social media monitoring, sentiment analysis, and brand reputation API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key",
      version: "v1.0",
      status: "ACTIVE",
      availability: "98.9%",
      throughput: "200 requests/minute",
      latency: "< 1000ms",
      securityLevel: "LOW",
      rateLimiting: "100 calls/hour per brand",
      documentation: "https://social.thermo-dynamics.com/api/docs",
      endpoint: "https://social.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-07-05"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // Service & Support Interfaces
    (knowledgeBaseApi:ApplicationInterface {
      id: "hp-interface-knowledge-base-api",
      name: "Knowledge Base API",
      interfaceType: "API",
      description: "Technical documentation, troubleshooting guides, and search API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key",
      version: "v2.0",
      status: "ACTIVE",
      availability: "99.4%",
      throughput: "1000 requests/minute",
      latency: "< 250ms",
      securityLevel: "LOW",
      rateLimiting: "2000 calls/hour per user",
      documentation: "https://kb.thermo-dynamics.com/api/docs",
      endpoint: "https://kb.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-11"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (warrantyApi:ApplicationInterface {
      id: "hp-interface-warranty-api",
      name: "Warranty Management API",
      interfaceType: "API",
      description: "Warranty registration, claims processing, and status tracking API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.9",
      status: "ACTIVE",
      availability: "99.6%",
      throughput: "300 requests/minute",
      latency: "< 400ms",
      securityLevel: "HIGH",
      rateLimiting: "150 calls/hour per customer",
      documentation: "https://warranty.thermo-dynamics.com/api/docs",
      endpoint: "https://warranty.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-08-07"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (serviceMobileApi:ApplicationInterface {
      id: "hp-interface-service-mobile-api",
      name: "Service Mobile API",
      interfaceType: "API",
      description: "Field service mobile app backend with work orders, diagnostics, and AR support",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + Device Cert",
      version: "v2.3",
      status: "ACTIVE",
      availability: "99.7%",
      throughput: "600 requests/minute",
      latency: "< 200ms",
      securityLevel: "HIGH",
      rateLimiting: "1000 calls/hour per technician",
      documentation: "https://fieldservice.thermo-dynamics.com/api/docs",
      endpoint: "https://fieldservice.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-19"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (sparePartsApi:ApplicationInterface {
      id: "hp-interface-spare-parts-api",
      name: "Spare Parts API",
      interfaceType: "API",
      description: "Spare parts inventory, ordering, and availability checking API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key",
      version: "v1.5",
      status: "ACTIVE",
      availability: "99.8%",
      throughput: "800 requests/minute",
      latency: "< 300ms",
      securityLevel: "MEDIUM",
      rateLimiting: "500 calls/hour per service center",
      documentation: "https://parts.thermo-dynamics.com/api/docs",
      endpoint: "https://parts.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-08-13"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // Business Support Interfaces
    (hrmsApi:ApplicationInterface {
      id: "hp-interface-hrms-api",
      name: "HRMS API",
      interfaceType: "API",
      description: "Human resources management, payroll, and employee data API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + MFA",
      version: "v3.1",
      status: "ACTIVE",
      availability: "99.9%",
      throughput: "400 requests/minute",
      latency: "< 300ms",
      securityLevel: "CRITICAL",
      rateLimiting: "200 calls/hour per HR user",
      documentation: "https://hr.thermo-dynamics.com/api/docs",
      endpoint: "https://hr.thermo-dynamics.com/api/v3",
      lastUpdated: date("2024-08-17"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (learningApi:ApplicationInterface {
      id: "hp-interface-learning-api",
      name: "Learning Management API",
      interfaceType: "API",
      description: "Employee training, certification tracking, and learning analytics API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v2.0",
      status: "ACTIVE",
      availability: "99.1%",
      throughput: "300 requests/minute",
      latency: "< 500ms",
      securityLevel: "MEDIUM",
      rateLimiting: "150 calls/hour per learner",
      documentation: "https://learning.thermo-dynamics.com/api/docs",
      endpoint: "https://learning.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-07-22"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (expenseApi:ApplicationInterface {
      id: "hp-interface-expense-api",
      name: "Expense Management API",
      interfaceType: "API",
      description: "Travel and expense reporting, approval workflows, and reimbursement API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.4",
      status: "ACTIVE",
      availability: "99.3%",
      throughput: "250 requests/minute",
      latency: "< 600ms",
      securityLevel: "HIGH",
      rateLimiting: "100 calls/hour per employee",
      documentation: "https://expenses.thermo-dynamics.com/api/docs",
      endpoint: "https://expenses.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-07-12"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (documentApi:ApplicationInterface {
      id: "hp-interface-document-api",
      name: "Document Management API",
      interfaceType: "API",
      description: "Enterprise document storage, search, and collaboration API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v2.2",
      status: "ACTIVE",
      availability: "99.5%",
      throughput: "1500 requests/minute",
      latency: "< 350ms",
      securityLevel: "MEDIUM",
      rateLimiting: "1000 calls/hour per user",
      documentation: "https://docs.thermo-dynamics.com/api/docs",
      endpoint: "https://docs.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-09"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (legalTechApi:ApplicationInterface {
      id: "hp-interface-legal-tech-api",
      name: "Legal Technology API",
      interfaceType: "API",
      description: "Contract management, legal compliance, and regulatory tracking API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + MFA",
      version: "v1.6",
      status: "ACTIVE",
      availability: "99.4%",
      throughput: "150 requests/minute",
      latency: "< 500ms",
      securityLevel: "HIGH",
      rateLimiting: "75 calls/hour per legal user",
      documentation: "https://legal.thermo-dynamics.com/api/docs",
      endpoint: "https://legal.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-08-06"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (cybersecurityApi:ApplicationInterface {
      id: "hp-interface-cybersecurity-api",
      name: "Cybersecurity Platform API",
      interfaceType: "API",
      description: "Security monitoring, threat detection, and incident response API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key + Certificate",
      version: "v3.0",
      status: "ACTIVE",
      availability: "99.95%",
      throughput: "2000 requests/minute",
      latency: "< 100ms",
      securityLevel: "CRITICAL",
      rateLimiting: "No limit for security systems",
      documentation: "Internal security documentation",
      endpoint: "https://security.thermo-dynamics.com/api/v3",
      lastUpdated: date("2024-08-21"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (backupApi:ApplicationInterface {
      id: "hp-interface-backup-api",
      name: "Backup & Recovery API",
      interfaceType: "API",
      description: "Backup management, disaster recovery, and data restoration API",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "API Key + MFA",
      version: "v2.1",
      status: "ACTIVE",
      availability: "99.9%",
      throughput: "100 requests/minute",
      latency: "< 1000ms",
      securityLevel: "CRITICAL",
      rateLimiting: "50 calls/hour per admin",
      documentation: "https://backup.thermo-dynamics.com/api/docs",
      endpoint: "https://backup.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-04"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // Analytics and BI Interfaces
    (biReportingApi:ApplicationInterface {
      id: "hp-interface-bi-reporting-api",
      name: "Business Intelligence Reporting API",
      interfaceType: "API",
      description: "API for business intelligence data access, report generation, and dashboard integration",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0",
      version: "v1.7",
      status: "ACTIVE",
      availability: "99.3%",
      throughput: "800 requests/minute",
      latency: "< 1500ms",
      securityLevel: "MEDIUM",
      rateLimiting: "50 calls/hour per user",
      documentation: "https://bi.thermo-dynamics.com/api/docs",
      endpoint: "https://bi.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-07-25"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (dataExportApi:ApplicationInterface {
      id: "hp-interface-data-export-api",
      name: "Data Export API",
      interfaceType: "API",
      description: "Bulk data export API for data warehousing, backup, and regulatory compliance reporting",
      protocol: "HTTPS",
      dataFormat: "JSON/CSV",
      authenticationMethod: "OAuth 2.0 + Admin Role",
      version: "v1.1",
      status: "ACTIVE",
      availability: "99.2%",
      throughput: "100 requests/minute",
      latency: "< 5000ms",
      securityLevel: "HIGH",
      rateLimiting: "10 calls/hour per admin",
      documentation: "https://api.thermo-dynamics.com/export/docs",
      endpoint: "https://api.thermo-dynamics.com/export/v1",
      lastUpdated: date("2024-05-20"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    // Mobile and Customer Interfaces
    (mobileCustomerApi:ApplicationInterface {
      id: "hp-interface-mobile-customer-api",
      name: "Mobile Customer App API",
      interfaceType: "API",
      description: "Mobile-optimized API for customer app providing heat pump control and monitoring",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + Biometric",
      version: "v2.3",
      status: "ACTIVE",
      availability: "99.7%",
      throughput: "5,000 requests/minute",
      latency: "< 300ms",
      securityLevel: "HIGH",
      rateLimiting: "1000 calls/hour per customer",
      documentation: "https://app.thermo-dynamics.com/api/docs",
      endpoint: "https://app.thermo-dynamics.com/api/v2",
      lastUpdated: date("2024-08-12"),
      createdAt: datetime(),
      updatedAt: datetime()
    }),

    (technicalSupportApi:ApplicationInterface {
      id: "hp-interface-technical-support-api",
      name: "Technical Support API",
      interfaceType: "API",
      description: "API for field technicians providing diagnostic tools, manuals, and remote assistance",
      protocol: "HTTPS",
      dataFormat: "JSON",
      authenticationMethod: "OAuth 2.0 + Employee ID",
      version: "v1.9",
      status: "ACTIVE",
      availability: "99.6%",
      throughput: "1,000 requests/minute",
      latency: "< 400ms",
      securityLevel: "HIGH",
      rateLimiting: "500 calls/hour per technician",
      documentation: "https://support.thermo-dynamics.com/api/docs",
      endpoint: "https://support.thermo-dynamics.com/api/v1",
      lastUpdated: date("2024-07-05"),
      createdAt: datetime(),
      updatedAt: datetime()
    })
  `

  try {
    await session.run(query)
    console.log('Application Interfaces created successfully.')
  } catch (error) {
    console.error('Error creating application interfaces:', error)
    throw error
  }
}

export async function createHeatPumpApplicationInterfaceOwnership(session: Session): Promise<void> {
  console.log('Creating Application Interface ownership relationships...')

  await session.run(`
    MATCH 
      (company:Company {id: "company-thermo-dynamics-ag"}),
      (cto:Person {id: "hp-person-cto"}),
      (cio:Person {id: "hp-person-cio"}),
      (itManager:Person {id: "hp-person-it-manager"}),
      (mfgDirector:Person {id: "hp-person-manufacturing-director"}),
      (salesDirector:Person {id: "hp-person-sales-director"}),
      (serviceDirector:Person {id: "hp-person-service-director"}),
      (productManager:Person {id: "hp-person-product-manager"}),
      (qualityManager:Person {id: "hp-person-quality-manager"}),
      (rdDirector:Person {id: "hp-person-rd-director"}),

      (iotDeviceApi:ApplicationInterface {id: "hp-interface-iot-device-api"}),
      (iotTelemetryApi:ApplicationInterface {id: "hp-interface-iot-telemetry-api"}),
      (energyAnalyticsApi:ApplicationInterface {id: "hp-interface-energy-analytics-api"}),
      (erpCustomerApi:ApplicationInterface {id: "hp-interface-erp-customer-api"}),
      (erpProductApi:ApplicationInterface {id: "hp-interface-erp-product-api"}),
      (erpOrderApi:ApplicationInterface {id: "hp-interface-erp-order-api"}),
      (crmServiceApi:ApplicationInterface {id: "hp-interface-crm-service-api"}),
      (crmInstallerApi:ApplicationInterface {id: "hp-interface-crm-installer-api"}),
      (mesProductionApi:ApplicationInterface {id: "hp-interface-mes-production-api"}),
      (qualityTestApi:ApplicationInterface {id: "hp-interface-quality-test-api"}),
      (supplierPortalApi:ApplicationInterface {id: "hp-interface-supplier-portal-api"}),
      (smartGridApi:ApplicationInterface {id: "hp-interface-smart-grid-api"}),
      (biReportingApi:ApplicationInterface {id: "hp-interface-bi-reporting-api"}),
      (dataExportApi:ApplicationInterface {id: "hp-interface-data-export-api"}),
      (mobileCustomerApi:ApplicationInterface {id: "hp-interface-mobile-customer-api"}),
      (technicalSupportApi:ApplicationInterface {id: "hp-interface-technical-support-api"})

    CREATE
      // Company ownership for all interfaces
      (iotDeviceApi)-[:OWNED_BY]->(company),
      (iotTelemetryApi)-[:OWNED_BY]->(company),
      (energyAnalyticsApi)-[:OWNED_BY]->(company),
      (erpCustomerApi)-[:OWNED_BY]->(company),
      (erpProductApi)-[:OWNED_BY]->(company),
      (erpOrderApi)-[:OWNED_BY]->(company),
      (crmServiceApi)-[:OWNED_BY]->(company),
      (crmInstallerApi)-[:OWNED_BY]->(company),
      (mesProductionApi)-[:OWNED_BY]->(company),
      (qualityTestApi)-[:OWNED_BY]->(company),
      (supplierPortalApi)-[:OWNED_BY]->(company),
      (smartGridApi)-[:OWNED_BY]->(company),
      (biReportingApi)-[:OWNED_BY]->(company),
      (dataExportApi)-[:OWNED_BY]->(company),
      (mobileCustomerApi)-[:OWNED_BY]->(company),
      (technicalSupportApi)-[:OWNED_BY]->(company),
      (strategyApi)-[:OWNED_BY]->(company),
      (riskMgmtApi)-[:OWNED_BY]->(company),
      (sustainabilityApi)-[:OWNED_BY]->(company),
      (marketIntelApi)-[:OWNED_BY]->(company),
      (plmApi)-[:OWNED_BY]->(company),
      (cfdApi)-[:OWNED_BY]->(company),
      (testDataApi)-[:OWNED_BY]->(company),
      (innovationApi)-[:OWNED_BY]->(company),
      (ipMgmtApi)-[:OWNED_BY]->(company),
      (mrpApi)-[:OWNED_BY]->(company),
      (warehouseApi)-[:OWNED_BY]->(company),
      (predictiveMaintenanceApi)-[:OWNED_BY]->(company),
      (energyMgmtApi)-[:OWNED_BY]->(company),
      (ecommerceApi)-[:OWNED_BY]->(company),
      (digitalMarketingApi)-[:OWNED_BY]->(company),
      (configuratorApi)-[:OWNED_BY]->(company),
      (partnerMobileApi)-[:OWNED_BY]->(company),
      (socialListeningApi)-[:OWNED_BY]->(company),
      (knowledgeBaseApi)-[:OWNED_BY]->(company),
      (warrantyApi)-[:OWNED_BY]->(company),
      (serviceMobileApi)-[:OWNED_BY]->(company),
      (sparePartsApi)-[:OWNED_BY]->(company),
      (hrmsApi)-[:OWNED_BY]->(company),
      (learningApi)-[:OWNED_BY]->(company),
      (expenseApi)-[:OWNED_BY]->(company),
      (documentApi)-[:OWNED_BY]->(company),
      (legalTechApi)-[:OWNED_BY]->(company),
      (cybersecurityApi)-[:OWNED_BY]->(company),
      (backupApi)-[:OWNED_BY]->(company),
      
      // Person ownership - ONLY ONE PERSON PER INTERFACE
      (iotDeviceApi)-[:OWNED_BY]->(cto),
      (iotTelemetryApi)-[:OWNED_BY]->(rdDirector),
      (energyAnalyticsApi)-[:OWNED_BY]->(cto),
      (erpCustomerApi)-[:OWNED_BY]->(cio),
      (erpProductApi)-[:OWNED_BY]->(productManager),
      (erpOrderApi)-[:OWNED_BY]->(salesDirector),
      (crmServiceApi)-[:OWNED_BY]->(serviceDirector),
      (crmInstallerApi)-[:OWNED_BY]->(salesDirector),
      (mesProductionApi)-[:OWNED_BY]->(mfgDirector),
      (qualityTestApi)-[:OWNED_BY]->(qualityManager),
      (supplierPortalApi)-[:OWNED_BY]->(mfgDirector),
      (smartGridApi)-[:OWNED_BY]->(cto),
      (biReportingApi)-[:OWNED_BY]->(cio),
      (dataExportApi)-[:OWNED_BY]->(cio),
      (mobileCustomerApi)-[:OWNED_BY]->(serviceDirector),
      (technicalSupportApi)-[:OWNED_BY]->(serviceDirector),
      
      // New Interface Ownership Assignments
      (strategyApi)-[:OWNED_BY]->(cio),
      (riskMgmtApi)-[:OWNED_BY]->(cio),
      (sustainabilityApi)-[:OWNED_BY]->(cto),
      (marketIntelApi)-[:OWNED_BY]->(productManager),
      (plmApi)-[:OWNED_BY]->(rdDirector),
      (cfdApi)-[:OWNED_BY]->(rdDirector),
      (testDataApi)-[:OWNED_BY]->(qualityManager),
      (innovationApi)-[:OWNED_BY]->(rdDirector),
      (ipMgmtApi)-[:OWNED_BY]->(rdDirector),
      (mrpApi)-[:OWNED_BY]->(mfgDirector),
      (warehouseApi)-[:OWNED_BY]->(mfgDirector),
      (predictiveMaintenanceApi)-[:OWNED_BY]->(mfgDirector),
      (energyMgmtApi)-[:OWNED_BY]->(mfgDirector),
      (ecommerceApi)-[:OWNED_BY]->(salesDirector),
      (digitalMarketingApi)-[:OWNED_BY]->(productManager),
      (configuratorApi)-[:OWNED_BY]->(salesDirector),
      (partnerMobileApi)-[:OWNED_BY]->(salesDirector),
      (socialListeningApi)-[:OWNED_BY]->(productManager),
      (knowledgeBaseApi)-[:OWNED_BY]->(serviceDirector),
      (warrantyApi)-[:OWNED_BY]->(serviceDirector),
      (serviceMobileApi)-[:OWNED_BY]->(serviceDirector),
      (sparePartsApi)-[:OWNED_BY]->(serviceDirector),
      (hrmsApi)-[:OWNED_BY]->(cio),
      (learningApi)-[:OWNED_BY]->(cio),
      (expenseApi)-[:OWNED_BY]->(cio),
      (documentApi)-[:OWNED_BY]->(cio),
      (legalTechApi)-[:OWNED_BY]->(cio),
      (cybersecurityApi)-[:OWNED_BY]->(cio),
      (backupApi)-[:OWNED_BY]->(cio)
  `)

  console.log('Application Interface ownership relationships created successfully.')
}

export async function createHeatPumpApplicationInterfaceConnections(
  session: Session
): Promise<void> {
  console.log('Creating Application-Interface connections...')

  await session.run(`
    MATCH 
      // Applications
      (iotPlatform:Application {id: "hp-app-iot-platform"}),
      (energyAnalytics:Application {id: "hp-app-energy-analytics"}),
      (erpSystem:Application {id: "hp-app-erp-system"}),
      (crmSystem:Application {id: "hp-app-crm-system"}),
      (mesSystem:Application {id: "hp-app-mes-system"}),
      (qualityManagement:Application {id: "hp-app-quality-management"}),
      (supplierPortal:Application {id: "hp-app-supplier-portal"}),
      (biPlatform:Application {id: "hp-app-bi-platform"}),
      (customerPortal:Application {id: "hp-app-customer-portal"}),
      (fieldServiceApp:Application {id: "hp-app-field-service"}),
      
      // Interfaces
      (iotDeviceApi:ApplicationInterface {id: "hp-interface-iot-device-api"}),
      (iotTelemetryApi:ApplicationInterface {id: "hp-interface-iot-telemetry-api"}),
      (energyAnalyticsApi:ApplicationInterface {id: "hp-interface-energy-analytics-api"}),
      (erpCustomerApi:ApplicationInterface {id: "hp-interface-erp-customer-api"}),
      (erpProductApi:ApplicationInterface {id: "hp-interface-erp-product-api"}),
      (erpOrderApi:ApplicationInterface {id: "hp-interface-erp-order-api"}),
      (crmServiceApi:ApplicationInterface {id: "hp-interface-crm-service-api"}),
      (crmInstallerApi:ApplicationInterface {id: "hp-interface-crm-installer-api"}),
      (mesProductionApi:ApplicationInterface {id: "hp-interface-mes-production-api"}),
      (qualityTestApi:ApplicationInterface {id: "hp-interface-quality-test-api"}),
      (supplierPortalApi:ApplicationInterface {id: "hp-interface-supplier-portal-api"}),
      (smartGridApi:ApplicationInterface {id: "hp-interface-smart-grid-api"}),
      (biReportingApi:ApplicationInterface {id: "hp-interface-bi-reporting-api"}),
      (dataExportApi:ApplicationInterface {id: "hp-interface-data-export-api"}),
      (mobileCustomerApi:ApplicationInterface {id: "hp-interface-mobile-customer-api"}),
      (technicalSupportApi:ApplicationInterface {id: "hp-interface-technical-support-api"})

    CREATE
      // IoT Platform provides interfaces
      (iotPlatform)-[:PROVIDES]->(iotDeviceApi),
      (iotPlatform)-[:PROVIDES]->(iotTelemetryApi),
      
      // Energy Analytics provides interface
      (energyAnalytics)-[:PROVIDES]->(energyAnalyticsApi),
      
      // ERP System provides interfaces
      (erpSystem)-[:PROVIDES]->(erpCustomerApi),
      (erpSystem)-[:PROVIDES]->(erpProductApi),
      (erpSystem)-[:PROVIDES]->(erpOrderApi),
      
      // CRM System provides interfaces
      (crmSystem)-[:PROVIDES]->(crmServiceApi),
      (crmSystem)-[:PROVIDES]->(crmInstallerApi),
      
      // MES System provides interface
      (mesSystem)-[:PROVIDES]->(mesProductionApi),
      
      // Quality Management provides interface
      (qualityManagement)-[:PROVIDES]->(qualityTestApi),
      
      // Supplier Portal provides interface
      (supplierPortal)-[:PROVIDES]->(supplierPortalApi),
      
      // BI Platform provides interfaces
      (biPlatform)-[:PROVIDES]->(biReportingApi),
      (biPlatform)-[:PROVIDES]->(dataExportApi),
      
      // Customer Portal provides interface
      (customerPortal)-[:PROVIDES]->(mobileCustomerApi),
      
      // Field Service provides interface
      (fieldServiceApp)-[:PROVIDES]->(technicalSupportApi),
      
      // IoT Platform also provides Smart Grid interface
      (iotPlatform)-[:PROVIDES]->(smartGridApi),
      
      // Cross-application interface consumption
      (crmSystem)-[:CONSUMES]->(erpCustomerApi),
      (customerPortal)-[:CONSUMES]->(iotDeviceApi),
      (customerPortal)-[:CONSUMES]->(energyAnalyticsApi),
      (fieldServiceApp)-[:CONSUMES]->(erpProductApi),
      (fieldServiceApp)-[:CONSUMES]->(crmServiceApi),
      (biPlatform)-[:CONSUMES]->(erpOrderApi),
      (biPlatform)-[:CONSUMES]->(mesProductionApi),
      (energyAnalytics)-[:CONSUMES]->(iotTelemetryApi),
      (supplierPortal)-[:CONSUMES]->(erpOrderApi),
      (mesSystem)-[:CONSUMES]->(erpProductApi)
  `)

  console.log('Application-Interface connections created successfully.')
}
