const schemaDigestArtifact = {
  artifact: 'schema-digest',
  version: '1.0.0',
  governance: {
    readOnly: true,
    dynamicQueryGenerationAllowed: false,
    permittedUses: {
      validation: true,
      capabilityAwareness: true,
      policyConstraints: true,
    },
  },
  mandatoryCompanyScoping: [
    {
      id: 'company-scope-company',
      appliesToRootQueries: [
        'businessCapabilities',
        'businessProcesses',
        'geaVisions',
        'geaMissions',
        'geaValues',
        'geaGoals',
        'geaStrategies',
        'suppliers',
        'applications',
        'applicationInterfaces',
        'dataObjects',
        'infrastructures',
        'softwareProducts',
        'softwareVersions',
        'hardwareProducts',
        'aiComponents',
        'organisations',
        'architectures',
        'architecturePrinciples',
        'businessCapabilitiesConnection',
        'businessProcessesConnection',
        'geaVisionsConnection',
        'geaMissionsConnection',
        'geaValuesConnection',
        'geaGoalsConnection',
        'geaStrategiesConnection',
        'suppliersConnection',
        'applicationsConnection',
        'applicationInterfacesConnection',
        'dataObjectsConnection',
        'infrastructuresConnection',
        'softwareProductsConnection',
        'softwareVersionsConnection',
        'hardwareProductsConnection',
        'aiComponentsConnection',
        'organisationsConnection',
        'architecturesConnection',
        'architecturePrinciplesConnection',
      ],
      requiredVariable: 'companyId',
      whereClauseShape: 'company: { some: { id: { eq: $companyId } } }',
      description: 'Default tenant scoping rule for graph-backed collections owned by a company.',
    },
    {
      id: 'people-company-scope',
      appliesToRootQueries: ['people', 'peopleConnection'],
      requiredVariable: 'companyId',
      whereClauseShape: 'companies: { some: { id: { eq: $companyId } } }',
      description:
        'People are scoped through the companies relation rather than the company relation.',
    },
    {
      id: 'company-root-id-scope',
      appliesToRootQueries: ['companies', 'companiesConnection'],
      requiredVariable: 'companyId',
      whereClauseShape: 'id: { eq: $companyId }',
      description: 'Company root queries are scoped directly by the selected company identifier.',
    },
  ],
  allowedRootQueries: [
    {
      rootQuery: 'businessCapabilities',
      entityType: 'BusinessCapability',
      whereType: 'BusinessCapabilityWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'maturityLevel',
        'status',
        'type',
        'businessValue',
        'sequenceNumber',
        'tags',
        'introductionDate',
        'endDate',
      ],
      relations: [
        'usedByOrganisations',
        'parents',
        'children',
        'supportedByApplications',
        'supportedByAIComponents',
        'supportedByBusinessProcesses',
        'relatedDataObjects',
      ],
    },
    {
      rootQuery: 'businessProcesses',
      entityType: 'BusinessProcess',
      whereType: 'BusinessProcessWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'processType',
        'status',
        'maturityLevel',
        'category',
        'tags',
      ],
      relations: [
        'usedByOrganisations',
        'parentProcess',
        'childProcesses',
        'supportsCapabilities',
        'supportedByApplications',
      ],
    },
    {
      rootQuery: 'geaVisions',
      entityType: 'GEA_Vision',
      whereType: 'GEA_VisionWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'visionStatement', 'timeHorizon', 'year'],
      relations: ['supportsMissions', 'supportedByGoals', 'supportedByValues'],
    },
    {
      rootQuery: 'geaMissions',
      entityType: 'GEA_Mission',
      whereType: 'GEA_MissionWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'purposeStatement', 'keywords', 'year'],
      relations: ['supportedByVisions', 'supportedByValues', 'supportedByGoals'],
    },
    {
      rootQuery: 'geaValues',
      entityType: 'GEA_Value',
      whereType: 'GEA_ValueWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'valueStatement'],
      relations: ['supportsMissions', 'supportsVisions'],
    },
    {
      rootQuery: 'geaGoals',
      entityType: 'GEA_Goal',
      whereType: 'GEA_GoalWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'goalStatement'],
      relations: [
        'operationalizesVisions',
        'supportsMissions',
        'supportsValues',
        'achievedByStrategies',
      ],
    },
    {
      rootQuery: 'geaStrategies',
      entityType: 'GEA_Strategy',
      whereType: 'GEA_StrategyWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'description'],
      relations: ['achievesGoals'],
    },
    {
      rootQuery: 'people',
      entityType: 'Person',
      whereType: 'PersonWhere',
      companyScopeRuleId: 'people-company-scope',
      fields: ['id', 'firstName', 'lastName', 'email', 'department', 'role', 'phone', 'avatarUrl'],
      relations: [
        'companies',
        'ownedCapabilities',
        'ownedApplications',
        'ownedDataObjects',
        'ownedArchitectures',
        'ownedInfrastructure',
        'ownedInterfaces',
        'ownedAIComponents',
        'ownedBusinessProcesses',
        'ownedGEAVisions',
        'ownedGEAMissions',
        'ownedGEAValues',
        'ownedGEAGoals',
        'ownedGEAStrategies',
      ],
    },
    {
      rootQuery: 'suppliers',
      entityType: 'Supplier',
      whereType: 'SupplierWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'supplierType',
        'status',
        'address',
        'phone',
        'email',
        'website',
        'primaryContactPerson',
        'contractStartDate',
        'contractEndDate',
        'annualSpend',
        'riskClassification',
        'strategicImportance',
        'performanceRating',
        'complianceCertifications',
        'tags',
      ],
      relations: [
        'providesApplications',
        'supportsApplications',
        'maintainsApplications',
        'providesAIComponents',
        'supportsAIComponents',
        'maintainsAIComponents',
        'providesInfrastructure',
        'hostsInfrastructure',
        'maintainsInfrastructure',
        'developsSoftwareProducts',
        'providesSoftwareProducts',
        'maintainsSoftwareProducts',
        'manufacturesHardwareProducts',
        'providesHardwareProducts',
        'maintainsHardwareProducts',
      ],
    },
    {
      rootQuery: 'applications',
      entityType: 'Application',
      whereType: 'ApplicationWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'status',
        'criticality',
        'timeCategory',
        'sevenRStrategy',
        'technologyStack',
        'version',
        'hostingEnvironment',
        'vendor',
        'costs',
        'introductionDate',
        'endOfLifeDate',
        'planningDate',
        'endOfUseDate',
      ],
      relations: [
        'usedByOrganisations',
        'parents',
        'components',
        'predecessors',
        'successors',
        'supportsCapabilities',
        'supportsBusinessProcesses',
        'usesDataObjects',
        'isDataSourceFor',
        'sourceOfInterfaces',
        'targetOfInterfaces',
        'hostedOn',
        'usesSoftwareProducts',
        'softwareVersions',
        'usesAIComponents',
        'providedBy',
        'supportedBy',
        'maintainedBy',
      ],
    },
    {
      rootQuery: 'applicationInterfaces',
      entityType: 'ApplicationInterface',
      whereType: 'ApplicationInterfaceWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'interfaceType',
        'protocol',
        'version',
        'status',
        'introductionDate',
        'endOfLifeDate',
        'planningDate',
        'endOfUseDate',
      ],
      relations: [
        'usedByOrganisations',
        'predecessors',
        'successors',
        'sourceApplications',
        'targetApplications',
        'dataObjects',
      ],
    },
    {
      rootQuery: 'dataObjects',
      entityType: 'DataObject',
      whereType: 'DataObjectWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'classification',
        'format',
        'introductionDate',
        'endOfLifeDate',
        'planningDate',
        'endOfUseDate',
      ],
      relations: [
        'usedByOrganisations',
        'dataSources',
        'usedByApplications',
        'relatedToCapabilities',
        'transferredInInterfaces',
        'usedForTrainingAI',
        'relatedDataObjects',
        'inverseRelatedDataObjects',
      ],
    },
    {
      rootQuery: 'infrastructures',
      entityType: 'Infrastructure',
      whereType: 'InfrastructureWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'infrastructureType',
        'status',
        'vendor',
        'version',
        'capacity',
        'location',
        'ipAddress',
        'operatingSystem',
        'specifications',
        'maintenanceWindow',
        'costs',
        'introductionDate',
        'endOfLifeDate',
        'planningDate',
        'endOfUseDate',
      ],
      relations: [
        'usedByOrganisations',
        'parentInfrastructure',
        'childInfrastructures',
        'hostsApplications',
        'hostsAIComponents',
        'usesSoftwareProducts',
        'usesHardwareProducts',
        'softwareVersions',
        'providedBy',
        'hostedBy',
        'maintainedBy',
      ],
    },
    {
      rootQuery: 'softwareProducts',
      entityType: 'SoftwareProduct',
      whereType: 'SoftwareProductWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'lifecycleStatus', 'isActive'],
      relations: [
        'usedByApplications',
        'usedByInfrastructure',
        'versions',
        'developedBy',
        'providedBy',
        'maintainedBy',
      ],
    },
    {
      rootQuery: 'softwareVersions',
      entityType: 'SoftwareVersion',
      whereType: 'SoftwareVersionWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'version', 'releaseChannel', 'isLts', 'supportTier'],
      relations: ['softwareProduct', 'usedByApplications', 'usedByInfrastructure'],
    },
    {
      rootQuery: 'hardwareProducts',
      entityType: 'HardwareProduct',
      whereType: 'HardwareProductWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'lifecycleStatus', 'isActive'],
      relations: ['usedByInfrastructure', 'manufacturedBy', 'providedBy', 'maintainedBy'],
    },
    {
      rootQuery: 'aiComponents',
      entityType: 'AIComponent',
      whereType: 'AIComponentWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'aiType',
        'model',
        'version',
        'status',
        'accuracy',
        'trainingDate',
        'lastUpdated',
        'provider',
        'license',
        'costs',
        'tags',
      ],
      relations: [
        'usedByOrganisations',
        'trainedWithDataObjects',
        'usedByApplications',
        'supportsCapabilities',
        'hostedOn',
        'providedBy',
        'supportedBy',
        'maintainedBy',
      ],
    },
    {
      rootQuery: 'companies',
      entityType: 'Company',
      whereType: 'CompanyWhere',
      companyScopeRuleId: 'company-root-id-scope',
      fields: [
        'id',
        'name',
        'description',
        'address',
        'website',
        'industry',
        'size',
        'primaryColor',
        'secondaryColor',
        'font',
        'diagramFont',
        'logo',
        'features',
        'llmUrl',
        'llmModel',
        'llmKey',
        'strategicAutonomyPriority',
        'resiliencePriority',
        'securityPriority',
        'controlPriority',
        'expectedSovereigntyScore',
        'achievedSovereigntyScore',
        'sovereigntyGap',
        'sovereigntyScorePercent',
        'sovereigntyScoreStatus',
      ],
      relations: [
        'organisations',
        'ownedCapabilities',
        'ownedApplications',
        'ownedDataObjects',
        'ownedInterfaces',
        'ownedInfrastructure',
        'ownedAIComponents',
        'ownedBusinessProcesses',
        'ownedGEAVisions',
        'ownedGEAMissions',
        'ownedGEAValues',
        'ownedGEAGoals',
        'ownedGEAStrategies',
        'employees',
        'ownedArchitectures',
        'ownedArchitecturePrinciples',
        'ownedSuppliers',
      ],
    },
    {
      rootQuery: 'organisations',
      entityType: 'Organisation',
      whereType: 'OrganisationWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: ['id', 'name', 'description', 'type', 'level'],
      relations: [
        'parentOrganisation',
        'childOrganisations',
        'usedCapabilities',
        'usedApplications',
        'usedDataObjects',
        'usedInterfaces',
        'usedInfrastructure',
        'usedAIComponents',
        'usedBusinessProcesses',
      ],
    },
    {
      rootQuery: 'architectures',
      entityType: 'Architecture',
      whereType: 'ArchitectureWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'timestamp',
        'domain',
        'type',
        'tags',
        'expectedSovereigntyScore',
        'achievedSovereigntyScore',
        'sovereigntyGap',
        'sovereigntyScorePercent',
      ],
      relations: [
        'containsCapabilities',
        'containsBusinessProcesses',
        'containsApplications',
        'containsDataObjects',
        'containsInterfaces',
        'containsInfrastructure',
        'containsAIComponents',
        'containsGEAVisions',
        'containsGEAMissions',
        'containsGEAValues',
        'containsGEAGoals',
        'containsGEAStrategies',
        'parentArchitecture',
        'childArchitectures',
        'appliedPrinciples',
      ],
    },
    {
      rootQuery: 'architecturePrinciples',
      entityType: 'ArchitecturePrinciple',
      whereType: 'ArchitecturePrincipleWhere',
      companyScopeRuleId: 'company-scope-company',
      fields: [
        'id',
        'name',
        'description',
        'category',
        'priority',
        'rationale',
        'implications',
        'tags',
        'isActive',
      ],
      relations: [
        'appliedInArchitectures',
        'implementedByApplications',
        'implementedByAIComponents',
      ],
    },
  ],
  countQueries: [
    {
      rootQuery: 'businessCapabilitiesConnection',
      entityType: 'BusinessCapability',
      whereType: 'BusinessCapabilityWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'businessProcessesConnection',
      entityType: 'BusinessProcess',
      whereType: 'BusinessProcessWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'geaVisionsConnection',
      entityType: 'GEA_Vision',
      whereType: 'GEA_VisionWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'geaMissionsConnection',
      entityType: 'GEA_Mission',
      whereType: 'GEA_MissionWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'geaValuesConnection',
      entityType: 'GEA_Value',
      whereType: 'GEA_ValueWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'geaGoalsConnection',
      entityType: 'GEA_Goal',
      whereType: 'GEA_GoalWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'geaStrategiesConnection',
      entityType: 'GEA_Strategy',
      whereType: 'GEA_StrategyWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'peopleConnection',
      entityType: 'Person',
      whereType: 'PersonWhere',
      companyScopeRuleId: 'people-company-scope',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'suppliersConnection',
      entityType: 'Supplier',
      whereType: 'SupplierWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'applicationsConnection',
      entityType: 'Application',
      whereType: 'ApplicationWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'applicationInterfacesConnection',
      entityType: 'ApplicationInterface',
      whereType: 'ApplicationInterfaceWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'dataObjectsConnection',
      entityType: 'DataObject',
      whereType: 'DataObjectWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'infrastructuresConnection',
      entityType: 'Infrastructure',
      whereType: 'InfrastructureWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'softwareProductsConnection',
      entityType: 'SoftwareProduct',
      whereType: 'SoftwareProductWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'softwareVersionsConnection',
      entityType: 'SoftwareVersion',
      whereType: 'SoftwareVersionWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'hardwareProductsConnection',
      entityType: 'HardwareProduct',
      whereType: 'HardwareProductWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'aiComponentsConnection',
      entityType: 'AIComponent',
      whereType: 'AIComponentWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'companiesConnection',
      entityType: 'Company',
      whereType: 'CompanyWhere',
      companyScopeRuleId: 'company-root-id-scope',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'organisationsConnection',
      entityType: 'Organisation',
      whereType: 'OrganisationWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'architecturesConnection',
      entityType: 'Architecture',
      whereType: 'ArchitectureWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
    {
      rootQuery: 'architecturePrinciplesConnection',
      entityType: 'ArchitecturePrinciple',
      whereType: 'ArchitecturePrincipleWhere',
      companyScopeRuleId: 'company-scope-company',
      resultPath: 'aggregate.count.nodes',
    },
  ],
  enumValues: {
    AIComponentStatus: [
      'IN_DEVELOPMENT',
      'TRAINING',
      'TESTING',
      'DEPLOYED',
      'ACTIVE',
      'DEPRECATED',
      'RETIRED',
    ],
    AIComponentType: [
      'MACHINE_LEARNING_MODEL',
      'DEEP_LEARNING_MODEL',
      'NATURAL_LANGUAGE_PROCESSING',
      'COMPUTER_VISION',
      'RECOMMENDATION_ENGINE',
      'PREDICTIVE_ANALYTICS',
      'CHATBOT',
      'VOICE_ASSISTANT',
      'DECISION_SUPPORT_SYSTEM',
      'AUTOMATION_ENGINE',
      'GENERATIVE_AI',
      'AGENTIC_AI',
      'RAG',
      'OTHER',
    ],
    ApplicationStatus: ['ACTIVE', 'IN_DEVELOPMENT', 'RETIRED'],
    ArchitectureDomain: [
      'BUSINESS',
      'DATA',
      'APPLICATION',
      'TECHNOLOGY',
      'SECURITY',
      'INTEGRATION',
      'ENTERPRISE',
    ],
    ArchitectureType: ['CURRENT_STATE', 'FUTURE_STATE', 'TRANSITION', 'CONCEPTUAL'],
    CapabilityStatus: ['ACTIVE', 'PLANNED', 'RETIRED'],
    CapabilityType: ['STRATEGIC', 'OPERATIONAL', 'SUPPORT'],
    CompanySize: ['STARTUP', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE', 'MULTINATIONAL'],
    CriticalityLevel: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    DataClassification: ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'STRICTLY_CONFIDENTIAL'],
    DiagramType: [
      'ARCHITECTURE',
      'APPLICATION_LANDSCAPE',
      'CAPABILITY_MAP',
      'DATA_FLOW',
      'PROCESS',
      'NETWORK',
      'INTEGRATION_ARCHITECTURE',
      'SECURITY_ARCHITECTURE',
      'CONCEPTUAL',
      'OTHER',
    ],
    InfrastructureStatus: [
      'ACTIVE',
      'INACTIVE',
      'MAINTENANCE',
      'PLANNED',
      'DECOMMISSIONED',
      'UNDER_CONSTRUCTION',
    ],
    InfrastructureType: [
      'CLOUD_DATACENTER',
      'ON_PREMISE_DATACENTER',
      'KUBERNETES_CLUSTER',
      'VIRTUALIZATION_CLUSTER',
      'VIRTUAL_MACHINE',
      'CONTAINER_HOST',
      'PHYSICAL_SERVER',
      'IOT_GATEWAY',
      'IOT_PLATFORM',
    ],
    InterfaceProtocol: [
      'REST',
      'SOAP',
      'GRAPHQL',
      'HTTP',
      'HTTPS',
      'FTP',
      'SFTP',
      'TCP',
      'UDP',
      'SMTP',
      'LDAP',
      'JDBC',
      'ODBC',
      'ORACLE',
      'MQTT',
      'OTHER',
    ],
    InterfaceStatus: ['ACTIVE', 'IN_DEVELOPMENT', 'OUT_OF_SERVICE', 'PLANNED', 'DEPRECATED'],
    InterfaceType: ['API', 'FILE', 'DATABASE', 'MESSAGE_QUEUE', 'OTHER'],
    LifecycleStatus: [
      'SUPPORTED',
      'APPROACHING_EOS',
      'APPROACHING_EOL',
      'EOS',
      'EOL',
      'UNSUPPORTED',
    ],
    OrganisationType: [
      'DIVISION',
      'DEPARTMENT',
      'TEAM',
      'PROJECT',
      'FUNCTION',
      'SUBSIDIARY',
      'BRANCH',
      'UNIT',
    ],
    PrincipleCategory: [
      'BUSINESS',
      'DATA',
      'APPLICATION',
      'TECHNOLOGY',
      'SECURITY',
      'INTEGRATION',
      'GOVERNANCE',
      'COMPLIANCE',
      'PERFORMANCE',
      'SCALABILITY',
      'RELIABILITY',
      'MAINTAINABILITY',
      'INTEROPERABILITY',
      'REUSABILITY',
      'FLEXIBILITY',
      'COST_OPTIMIZATION',
    ],
    PrinciplePriority: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    ProcessStatus: ['ACTIVE', 'PLANNED', 'RETIRED'],
    ProcessType: ['CORE', 'SUPPORT', 'MANAGEMENT'],
    ProductFamilyCategory: [
      'COMPUTE_END_USER_DEVICES',
      'NETWORK_DEVICES',
      'STORAGE_DATA_INFRASTRUCTURE',
      'SECURITY_HARDWARE',
      'PERIPHERALS_OUTPUT_DEVICES',
      'DATA_CENTER_INFRASTRUCTURE',
      'OPERATING_PLATFORM_SOFTWARE',
      'INFRASTRUCTURE_PLATFORM_SOFTWARE',
      'CLOUD_PLATFORM_SERVICES',
      'SECURITY_SOFTWARE',
      'MANAGEMENT_OPERATIONS_SOFTWARE',
      'END_USER_COLLABORATION_SOFTWARE',
      'DEVELOPMENT_ENGINEERING_SOFTWARE',
      'BUSINESS_ENTERPRISE_APPLICATIONS',
    ],
    ProductFamilyType: ['HARDWARE', 'SOFTWARE'],
    RiskClassification: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    SevenRStrategy: [
      'RETIRE',
      'RETAIN',
      'REHOST',
      'REPLATFORM',
      'REFACTOR',
      'REARCHITECT',
      'REPLACE',
    ],
    SovereigntyMaturity: ['NONE', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH'],
    StrategicImportance: ['LOW', 'MEDIUM', 'HIGH', 'STRATEGIC'],
    SupplierStatus: ['ACTIVE', 'POTENTIAL', 'INACTIVE', 'BLOCKED'],
    SupplierType: [
      'SOFTWARE_VENDOR',
      'SERVICE_PROVIDER',
      'CONSULTANT',
      'HARDWARE_VENDOR',
      'CLOUD_PROVIDER',
    ],
    TimeCategory: ['TOLERATE', 'INVEST', 'MIGRATE', 'ELIMINATE'],
  },
  filterSyntax: {
    stringOperators: ['contains', 'eq', 'startsWith'],
    enumOperators: ['eq', 'in'],
    nullOperators: ['isNull'],
    relationOperators: ['some', 'none'],
    logicalOperators: ['AND', 'OR'],
    paginationArguments: ['limit', 'offset', 'sort'],
    notes: [
      'SCHEMA_DIGEST is a read-only governance contract and must not be used to dynamically generate GraphQL documents.',
      'Use this artifact only for validation, capability awareness, and policy constraints.',
      'Every governed query must include the mandatory company scope defined by its companyScopeRuleId.',
      'Filter examples describe the allowed syntax surface; they do not authorize arbitrary new root queries.',
    ],
    examples: [
      '{ name: { contains: "CRM" } }',
      '{ status: { eq: ACTIVE } }',
      '{ status: { in: [ACTIVE, PLANNED] } }',
      '{ description: { isNull: false } }',
      '{ supportsCapabilities: { some: { name: { contains: "CRM" } } } }',
      '{ supportedByApplications: { none: {} } }',
      '{ AND: [{ status: { eq: ACTIVE } }, { criticality: { eq: HIGH } }] }',
      '{ OR: [{ name: { contains: "ERP" } }, { name: { contains: "SAP" } }] }',
      'company: { some: { id: { eq: $companyId } } }',
      'companies: { some: { id: { eq: $companyId } } }',
      'id: { eq: $companyId }',
    ],
  },
} as const

export { schemaDigestArtifact }
export default schemaDigestArtifact
