{{- if and .Values.client.brandingAssets.enabled (not .Values.client.brandingAssets.existingConfigMap) }}
{{- $fullName := include "nextgen-eam.fullname" . -}}
{{- $labels := include "nextgen-eam.labels" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-client-branding-assets
  labels: {{- $labels | nindent 4 }}
binaryData:
  {{ .Values.client.brandingAssets.archiveFileName }}: {{ .Files.Get (printf "assets/%s" .Values.client.brandingAssets.archiveFileName) | b64enc }}
{{- end }}
