{{- if and .Values.keycloak.theme.enabled (not .Values.keycloak.theme.existingConfigMap) }}
{{- $fullName := include "nextgen-eam.fullname" . -}}
{{- $labels := include "nextgen-eam.labels" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-keycloak-theme-assets
  labels: {{- $labels | nindent 4 }}
binaryData:
  {{ .Values.keycloak.theme.archiveFileName }}: {{ .Files.Get (printf "assets/%s" .Values.keycloak.theme.archiveFileName) | b64enc }}
{{- end }}
